# Generated by Django 3.0.8 on 2020-07-25 17:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BR', unique=True, verbose_name='Telefone'),
        ),
    ]
